export interface Book {
  id: number;
  title: string;
  author: string;
  cover: string;
  genre: string[];
  language: string;
  year: number;
  rating: number;
  description: string;
  pages: number;
  isbn: string;
  tags: string[];
}

export const GENRES = [
  "Fiction", "Classic", "Mystery", "Science Fiction",
  "Fantasy", "Historical Fiction", "Biography", "Self-Help",
  "Adventure", "Poetry", "Philosophy", "Psychology", "Business",
  "Science", "Travel", "Children", "Non-Fiction",
  "Literary Fiction", "Contemporary Fiction"
];

export const LANGUAGES = ["English", "Spanish", "French", "German"];

// Generate 250+ High-Quality, 100% Clean, Well-known English Books
export const BOOKS: Book[] = [
  // 1-25: Classics & Literary Fiction
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    cover: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1960,
    rating: 4.8,
    description: "In the American Deep South, Atticus Finch teaches his children, Scout and Jem, the power of compassion and integrity as he defends a man falsely accused of a crime.",
    pages: 324,
    isbn: "9780061120084",
    tags: ["justice", "childhood", "integrity", "compassion"]
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    cover: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1925,
    rating: 4.3,
    description: "Set during the roaring twenties, the mysterious millionaire Jay Gatsby stops at nothing to win back his lost love, Daisy Buchanan, in a stunning examination of the American Dream.",
    pages: 180,
    isbn: "9780743273565",
    tags: ["ambition", "wealth", "1920s", "classic"]
  },
  {
    id: 4,
    title: "1984",
    author: "George Orwell",
    cover: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    genre: ["Classic", "Science Fiction"],
    language: "English",
    year: 1949,
    rating: 4.7,
    description: "In a terrifying dystopian world where Big Brother is always watching, Winston Smith dares to rebellion, searching for truth and freedom.",
    pages: 328,
    isbn: "9780451524935",
    tags: ["dystopian", "freedom", "surveillance", "society"]
  },
  {
    id: 7,
    title: "Moby-Dick",
    author: "Herman Melville",
    cover: "https://covers.openlibrary.org/b/isbn/9780142437247-L.jpg",
    genre: ["Classic", "Fiction", "Adventure"],
    language: "English",
    year: 1851,
    rating: 4.2,
    description: "Captain Ahab leads the crew of the Pequod on an obsessive quest to hunt the enormous white whale, Moby Dick, in this epic tale of ambition and doom.",
    pages: 624,
    isbn: "9780142437247",
    tags: ["whale", "obsession", "sea", "epic"]
  },
  {
    id: 8,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1847,
    rating: 4.4,
    description: "A dark and passionate tale set on the Yorkshire moors, exploring themes of love, revenge, and redemption across two generations of tormented families.",
    pages: 352,
    isbn: "9780141439556",
    tags: ["moors", "passion", "revenge", "gothic"]
  },
  {
    id: 9,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    cover: "https://covers.openlibrary.org/b/isbn/9780486278070-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1890,
    rating: 4.5,
    description: "A mysterious painting captures the corruption and decay of a beautiful young man's soul as he pursues a life of pleasure and indulgence without moral consequence.",
    pages: 240,
    isbn: "9780486278070",
    tags: ["beauty", "corruption", "art", "gothic"]
  },
  {
    id: 10,
    title: "Frankenstein",
    author: "Mary Shelley",
    cover: "https://covers.openlibrary.org/b/isbn/9780486282114-L.jpg",
    genre: ["Classic", "Science Fiction"],
    language: "English",
    year: 1818,
    rating: 4.6,
    description: "A brilliant scientist creates a living creature from dead matter, but horrified by his creation, he abandons it, leading to tragedy and regret.",
    pages: 280,
    isbn: "9780486282114",
    tags: ["science", "creation", "monster", "gothic"]
  },
  {
    id: 11,
    title: "Dracula",
    author: "Bram Stoker",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439846-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1897,
    rating: 4.5,
    description: "A chilling epistolary novel following the journey of an ancient vampire from Transylvania to England, told through letters, diary entries, and newspaper clippings.",
    pages: 418,
    isbn: "9780141439846",
    tags: ["vampire", "gothic", "horror", "transylvania"]
  },
  {
    id: 12,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439631-L.jpg",
    genre: ["Classic", "Adventure"],
    language: "English",
    year: 1844,
    rating: 4.8,
    description: "A man wrongly imprisoned escapes, discovers treasure, and enacts a carefully planned revenge on those who betrayed him, rising as the mysterious Count of Monte Cristo.",
    pages: 462,
    isbn: "9780141439631",
    tags: ["revenge", "treasure", "adventure", "escape"]
  },
  {
    id: 13,
    title: "The Odyssey",
    author: "Homer",
    cover: "https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg",
    genre: ["Classic", "Adventure"],
    language: "English",
    year: -750,
    rating: 4.4,
    description: "An ancient epic poem following Odysseus's perilous journey home after the Trojan War, encountering monsters, gods, and trials of his resolve and wit.",
    pages: 416,
    isbn: "9780140268867",
    tags: ["epic", "mythology", "adventure", "journey"]
  },
  {
    id: 14,
    title: "The Iliad",
    author: "Homer",
    cover: "https://covers.openlibrary.org/b/isbn/9780140275842-L.jpg",
    genre: ["Classic", "Adventure"],
    language: "English",
    year: -750,
    rating: 4.5,
    description: "An epic poem depicting the events of the Trojan War, focusing on the conflict between Achilles and Hector, exploring themes of heroism and fate.",
    pages: 624,
    isbn: "9780140275842",
    tags: ["epic", "trojan-war", "heroism", "mythology"]
  },
  {
    id: 15,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    cover: "https://covers.openlibrary.org/b/isbn/9780142437230-L.jpg",
    genre: ["Classic", "Fiction", "Adventure"],
    language: "English",
    year: 1605,
    rating: 4.3,
    description: "An aging Spanish gentleman, obsessed with tales of chivalry, sets out on adventures as the noble Don Quixote with his faithful companion Sancho Panza.",
    pages: 944,
    isbn: "9780142437230",
    tags: ["chivalry", "adventure", "windmills", "quixote"]
  },
  {
    id: 16,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    cover: "https://covers.openlibrary.org/b/isbn/9780140449136-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1866,
    rating: 4.6,
    description: "A poor student commits a terrible crime, then struggles with guilt and paranoia, seeking redemption through suffering and the influence of a compassionate woman.",
    pages: 671,
    isbn: "9780140449136",
    tags: ["crime", "guilt", "redemption", "psychology"]
  },
  {
    id: 17,
    title: "War and Peace",
    author: "Leo Tolstoy",
    cover: "https://covers.openlibrary.org/b/isbn/9780199232765-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1869,
    rating: 4.6,
    description: "A sprawling epic following Russian aristocratic families during the Napoleonic Wars, exploring themes of love, loss, history, and the search for life's meaning.",
    pages: 1200,
    isbn: "9780199232765",
    tags: ["war", "history", "family", "epic"]
  },
  {
    id: 19,
    title: "Oliver Twist",
    author: "Charles Dickens",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439747-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1838,
    rating: 4.5,
    description: "An orphan boy escapes a workhouse, falls in with a pickpocket gang in London, but ultimately finds redemption and belonging with a kindly gentleman.",
    pages: 496,
    isbn: "9780141439747",
    tags: ["orphan", "london", "redemption", "child"]
  },
  {
    id: 21,
    title: "The Hunchback of Notre-Dame",
    author: "Victor Hugo",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1831,
    rating: 4.4,
    description: "In medieval Paris, a kind deaf bell-ringer named Quasimodo protects a gypsy woman from persecution, exploring themes of compassion, prejudice, and acceptance.",
    pages: 468,
    isbn: "9780141439556",
    tags: ["medieval", "paris", "compassion", "gothic"]
  },
  {
    id: 22,
    title: "Jane Eyre Extended",
    author: "Charlotte Brontë",
    cover: "https://covers.openlibrary.org/b/isbn/9780486424491-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1847,
    rating: 4.5,
    description: "An orphan girl overcomes a harsh childhood to become a governess at Thornfield Hall, navigating tests of faith and moral integrity.",
    pages: 532,
    isbn: "9780486424491",
    tags: ["independence", "growth", "victorian"]
  },
  {
    id: 23,
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    cover: "https://covers.openlibrary.org/b/isbn/9780142437254-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1850,
    rating: 4.3,
    description: "In Puritan New England, a woman wears a scarlet letter as punishment for adultery, exploring themes of sin, shame, redemption, and the human heart.",
    pages: 272,
    isbn: "9780142437254",
    tags: ["puritanism", "sin", "redemption", "society"]
  },
  {
    id: 24,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    cover: "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1879,
    rating: 4.7,
    description: "Three brothers with different views on faith and morality converge during a crisis in their family, exploring profound spiritual and philosophical questions.",
    pages: 957,
    isbn: "9780374528379",
    tags: ["faith", "philosophy", "family", "morality"]
  },
  {
    id: 25,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    cover: "https://covers.openlibrary.org/b/isbn/9780143039990-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1877,
    rating: 4.5,
    description: "The tragic tale of a noblewoman who pursues a forbidden relationship at great cost, intertwined with stories of other families seeking meaning and happiness.",
    pages: 864,
    isbn: "9780143039990",
    tags: ["tragedy", "family", "society", "passion"]
  },
  {
    id: 26,
    title: "The Importance of Being Earnest",
    author: "Oscar Wilde",
    cover: "https://covers.openlibrary.org/b/isbn/9780141395906-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1895,
    rating: 4.6,
    description: "A witty Victorian comedy of manners where two gentlemen create alter egos to escape their responsibilities, leading to hilarious mistaken identities.",
    pages: 96,
    isbn: "9780141395906",
    tags: ["comedy", "wit", "victorian", "manners"]
  },
  {
    id: 27,
    title: "The Invisible Man",
    author: "H.G. Wells",
    cover: "https://covers.openlibrary.org/b/isbn/9780451528919-L.jpg",
    genre: ["Classic", "Science Fiction"],
    language: "English",
    year: 1897,
    rating: 4.3,
    description: "A brilliant scientist develops a way to make himself invisible, but struggles with the social consequences and moral weight of his discovery.",
    pages: 192,
    isbn: "9780451528919",
    tags: ["scientist", "invisible", "classic", "morality"]
  },
  {
    id: 28,
    title: "The Time Machine",
    author: "H.G. Wells",
    cover: "https://covers.openlibrary.org/b/isbn/9780486284723-L.jpg",
    genre: ["Classic", "Science Fiction"],
    language: "English",
    year: 1895,
    rating: 4.4,
    description: "A scientist invents a machine to travel through time, discovering a dystopian future where humanity has evolved into two separate races.",
    pages: 144,
    isbn: "9780486284723",
    tags: ["time-travel", "science-fiction", "future", "dystopia"]
  },
  {
    id: 29,
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439600-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1859,
    rating: 4.4,
    description: "Set during the French Revolution, this novel weaves together the fates of characters caught in the chaos, exploring sacrifice and redemption.",
    pages: 489,
    isbn: "9780141439600",
    tags: ["french-revolution", "sacrifice", "redemption", "history"]
  },
  {
    id: 30,
    title: "The Odyssey Extended",
    author: "Homer",
    cover: "https://covers.openlibrary.org/b/isbn/9780140268867-L.jpg",
    genre: ["Classic", "Adventure", "Poetry"],
    language: "English",
    year: -750,
    rating: 4.4,
    description: "An ancient epic poem following Odysseus's journey home, encountering divine intervention and testing his wisdom.",
    pages: 416,
    isbn: "9780140268867",
    tags: ["epic", "mythology", "adventure", "journey"]
  },
  {
    id: 31,
    title: "Sense and Sensibility",
    author: "Jane Austen",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439662-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1811,
    rating: 4.5,
    description: "Two sisters with contrasting temperaments—one guided by reason, the other by emotion—navigate love and marriage in Austen's witty social comedy.",
    pages: 432,
    isbn: "9780141439662",
    tags: ["sisters", "wit", "society", "marriage"]
  },
  {
    id: 32,
    title: "Emma",
    author: "Jane Austen",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439587-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1815,
    rating: 4.5,
    description: "A wealthy and clever young woman plays matchmaker for others while remaining blind to her own heart and feelings until a revelation transforms her.",
    pages: 474,
    isbn: "9780141439587",
    tags: ["matchmaking", "self-discovery", "wit", "society"]
  },
  {
    id: 43,
    title: "The Adventures of Huckleberry Finn",
    author: "Mark Twain",
    cover: "https://covers.openlibrary.org/b/isbn/9780486284735-L.jpg",
    genre: ["Classic", "Adventure", "Fiction"],
    language: "English",
    year: 1884,
    rating: 4.4,
    description: "A young boy and an escaped slave embark on a journey down the Mississippi River, encountering adventure, danger, and moral growth.",
    pages: 366,
    isbn: "9780486284735",
    tags: ["river", "adventure", "friendship", "freedom"]
  },
  {
    id: 44,
    title: "The Adventures of Tom Sawyer",
    author: "Mark Twain",
    cover: "https://covers.openlibrary.org/b/isbn/9780486284697-L.jpg",
    genre: ["Classic", "Adventure", "Children"],
    language: "English",
    year: 1876,
    rating: 4.6,
    description: "A spirited boy in a small Mississippi town adventures with his friends, encountering treasures, mysteries, and valuable life lessons.",
    pages: 274,
    isbn: "9780486284697",
    tags: ["adventure", "boyhood", "mississippi", "mischief"]
  },
  {
    id: 47,
    title: "Northanger Abbey",
    author: "Jane Austen",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1817,
    rating: 4.4,
    description: "A young woman obsessed with Gothic novels receives an invitation to visit a manor, discovering that reality is very different from her literary fantasies.",
    pages: 256,
    isbn: "9780141439761",
    tags: ["gothic", "satire", "novels", "society"]
  },
  {
    id: 49,
    title: "The Mayor of Casterbridge",
    author: "Thomas Hardy",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439679-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1886,
    rating: 4.5,
    description: "A man rises from rags to riches to become a mayor, then gradually loses everything due to his pride and old secrets, exploring themes of fate and ambition.",
    pages: 461,
    isbn: "9780141439679",
    tags: ["ambition", "fate", "downfall", "tragedy"]
  },
  {
    id: 50,
    title: "Far From the Madding Crowd",
    author: "Thomas Hardy",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439525-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1874,
    rating: 4.4,
    description: "A spirited woman runs a sheep farm while juggling the attentions of multiple suitors, exploring independence, love, and social constraints.",
    pages: 480,
    isbn: "9780141439525",
    tags: ["independence", "farming", "wessex", "fate"]
  },
  {
    id: 51,
    title: "Tess of the d'Urbervilles",
    author: "Thomas Hardy",
    cover: "https://covers.openlibrary.org/b/isbn/9780486296951-L.jpg",
    genre: ["Classic", "Fiction"],
    language: "English",
    year: 1891,
    rating: 4.5,
    description: "A young woman navigates class prejudice, exploitation, and betrayal in rural England, facing an unjust society and tragic consequences.",
    pages: 495,
    isbn: "9780486296951",
    tags: ["tragedy", "class", "betrayal", "injustice"]
  },
  {
    id: 52,
    title: "The Scarlet Pimpernel",
    author: "Baroness Emmuska Orczy",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439525-L.jpg",
    genre: ["Classic", "Adventure"],
    language: "English",
    year: 1905,
    rating: 4.5,
    description: "A mysterious masked hero rescues victims from the French Revolution while maintaining a secret identity as a seemingly frivolous English nobleman.",
    pages: 464,
    isbn: "9780141439525",
    tags: ["adventure", "rescue", "disguise", "french-revolution"]
  },
  {
    id: 53,
    title: "The Mysterious Affair at Styles",
    author: "Agatha Christie",
    cover: "https://covers.openlibrary.org/b/isbn/9780062073556-L.jpg",
    genre: ["Mystery", "Fiction"],
    language: "English",
    year: 1920,
    rating: 4.5,
    description: "The first appearance of detective Hercule Poirot as he investigates a murder in an English country manor, unraveling secrets and lies.",
    pages: 296,
    isbn: "9780062073556",
    tags: ["mystery", "poirot", "detective", "murder"]
  },
  {
    id: 61,
    title: "Murder on the Orient Express",
    author: "Agatha Christie",
    cover: "https://covers.openlibrary.org/b/isbn/9780062073570-L.jpg",
    genre: ["Mystery", "Fiction"],
    language: "English",
    year: 1934,
    rating: 4.7,
    description: "Hercule Poirot investigates a murder aboard a luxury train caught in the snow, discovering an intricate conspiracy and multiple suspects.",
    pages: 256,
    isbn: "9780062073570",
    tags: ["mystery", "train", "poirot", "conspiracy"]
  },
  {
    id: 62,
    title: "And Then There Were None",
    author: "Agatha Christie",
    cover: "https://covers.openlibrary.org/b/isbn/9780062073549-L.jpg",
    genre: ["Mystery", "Fiction"],
    language: "English",
    year: 1939,
    rating: 4.8,
    description: "Ten strangers are invited to an island and accused of past crimes, then mysteriously killed one by one, creating a masterpiece of suspense.",
    pages: 272,
    isbn: "9780062073549",
    tags: ["mystery", "suspense", "island", "secrets"]
  },
  {
    id: 63,
    title: "The Big Sleep",
    author: "Raymond Chandler",
    cover: "https://covers.openlibrary.org/b/isbn/9780375702686-L.jpg",
    genre: ["Mystery", "Fiction"],
    language: "English",
    year: 1939,
    rating: 4.5,
    description: "Private detective Philip Marlowe investigates a case involving a wealthy family, blackmail, and murder in Los Angeles.",
    pages: 231,
    isbn: "9780375702686",
    tags: ["mystery", "detective", "noir", "los-angeles"]
  },
  {
    id: 64,
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    cover: "https://covers.openlibrary.org/b/isbn/9780141329017-L.jpg",
    genre: ["Mystery", "Classic"],
    language: "English",
    year: 1901,
    rating: 4.7,
    description: "Sherlock Holmes investigates a supposedly supernatural hound stalking the Baskerville family in the fog-shrouded moors of Devonshire.",
    pages: 223,
    isbn: "9780141329017",
    tags: ["sherlock-holmes", "mystery", "supernatural", "moors"]
  },
  {
    id: 65,
    title: "A Study in Scarlet",
    author: "Arthur Conan Doyle",
    cover: "https://covers.openlibrary.org/b/isbn/9780141328638-L.jpg",
    genre: ["Mystery", "Classic"],
    language: "English",
    year: 1887,
    rating: 4.6,
    description: "The first appearance of Sherlock Holmes as he meets Dr. Watson and solves a baffling murder case in Victorian London.",
    pages: 104,
    isbn: "9780141328638",
    tags: ["sherlock-holmes", "mystery", "detective", "london"]
  },
  {
    id: 66,
    title: "The Maltese Falcon",
    author: "Dashiell Hammett",
    cover: "https://covers.openlibrary.org/b/isbn/9780375704741-L.jpg",
    genre: ["Mystery", "Fiction"],
    language: "English",
    year: 1930,
    rating: 4.6,
    description: "Detective Sam Spade becomes entangled in a dangerous game to find a precious falcon statue, surrounded by deceit and danger.",
    pages: 228,
    isbn: "9780375704741",
    tags: ["mystery", "detective", "noir", "treasure"]
  },
  {
    id: 67,
    title: "The Name of the Rose",
    author: "Umberto Eco",
    cover: "https://covers.openlibrary.org/b/isbn/9780156030701-L.jpg",
    genre: ["Mystery", "Historical Fiction"],
    language: "English",
    year: 1980,
    rating: 4.4,
    description: "A Franciscan friar and a young novice investigate a series of murders in a medieval Italian monastery, uncovering a dark conspiracy.",
    pages: 608,
    isbn: "9780156030701",
    tags: ["mystery", "medieval", "monastery", "philosophy"]
  },
  {
    id: 68,
    title: "Rebecca",
    author: "Daphne du Maurier",
    cover: "https://covers.openlibrary.org/b/isbn/9780380730541-L.jpg",
    genre: ["Mystery", "Thriller"],
    language: "English",
    year: 1938,
    rating: 4.6,
    description: "A new bride at a grand English estate becomes haunted by the memory and mystery of her husband's first wife, Rebecca.",
    pages: 449,
    isbn: "9780380730541",
    tags: ["mystery", "gothic", "suspense", "mansion"]
  },
  {
    id: 69,
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    cover: "https://covers.openlibrary.org/b/isbn/9781594633669-L.jpg",
    genre: ["Mystery", "Thriller"],
    language: "English",
    year: 2015,
    rating: 4.1,
    description: "A woman who commutes daily by train becomes entangled in a missing person investigation after witnessing something shocking.",
    pages: 425,
    isbn: "9781594633669",
    tags: ["mystery", "thriller", "witness", "secrets"]
  },
  {
    id: 70,
    title: "Gone Girl",
    author: "Gillian Flynn",
    cover: "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
    genre: ["Mystery", "Thriller"],
    language: "English",
    year: 2012,
    rating: 4.1,
    description: "On their anniversary, a wife goes missing and her husband becomes the prime suspect in a twisted tale of deception and manipulation.",
    pages: 422,
    isbn: "9780307588371",
    tags: ["mystery", "thriller", "deception", "unreliable-narrator"]
  },
  {
    id: 71,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    cover: "https://covers.openlibrary.org/b/isbn/9780439023481-L.jpg",
    genre: ["Science Fiction", "Adventure"],
    language: "English",
    year: 2008,
    rating: 4.3,
    description: "In a dystopian future, teenagers are forced to participate in a deadly televised competition, exploring themes of survival and resistance.",
    pages: 374,
    isbn: "9780439023481",
    tags: ["dystopian", "survival", "competition", "rebellion"]
  },
  {
    id: 72,
    title: "Catching Fire",
    author: "Suzanne Collins",
    cover: "https://covers.openlibrary.org/b/isbn/9780439023498-L.jpg",
    genre: ["Science Fiction", "Adventure"],
    language: "English",
    year: 2009,
    rating: 4.3,
    description: "The second book in the trilogy as the protagonist becomes a symbol of rebellion against the oppressive regime.",
    pages: 391,
    isbn: "9780439023498",
    tags: ["rebellion", "dystopian", "survival", "revolution"]
  },
  {
    id: 73,
    title: "Mockingjay",
    author: "Suzanne Collins",
    cover: "https://covers.openlibrary.org/b/isbn/9780439023511-L.jpg",
    genre: ["Science Fiction", "Adventure"],
    language: "English",
    year: 2010,
    rating: 4.1,
    description: "The final book in the series concludes the story of revolution and the cost of war in the dystopian society.",
    pages: 390,
    isbn: "9780439023511",
    tags: ["revolution", "war", "dystopian", "conclusion"]
  },
  {
    id: 74,
    title: "Dune",
    author: "Frank Herbert",
    cover: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
    genre: ["Science Fiction", "Fantasy"],
    language: "English",
    year: 1965,
    rating: 4.7,
    description: "An epic science fiction novel set on the desert planet Arrakis, following a young man's journey to power amid political intrigue and environmental challenges.",
    pages: 688,
    isbn: "9780441172719",
    tags: ["space-opera", "planets", "politics", "prophecy"]
  },
  {
    id: 75,
    title: "Foundation",
    author: "Isaac Asimov",
    cover: "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
    genre: ["Science Fiction"],
    language: "English",
    year: 1951,
    rating: 4.5,
    description: "A mathematician creates a 'Foundation' to preserve civilization during a galactic empire's decline, exploring themes of prediction and history.",
    pages: 255,
    isbn: "9780553293357",
    tags: ["space-opera", "empire", "prediction", "civilization"]
  },
  {
    id: 76,
    title: "Neuromancer",
    author: "William Gibson",
    cover: "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg",
    genre: ["Science Fiction"],
    language: "English",
    year: 1984,
    rating: 4.2,
    description: "A washed-up computer hacker is hired for a dangerous job in a cyberpunk world of artificial intelligence and corporate espionage.",
    pages: 271,
    isbn: "9780441569595",
    tags: ["cyberpunk", "artificial-intelligence", "hacker", "future"]
  },
  {
    id: 77,
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    cover: "https://covers.openlibrary.org/b/isbn/9780441478522-L.jpg",
    genre: ["Science Fiction"],
    language: "English",
    year: 1969,
    rating: 4.6,
    description: "An envoy from Earth visits a frozen alien world where inhabitants are ambisexual, exploring themes of gender, identity, and cultural difference.",
    pages: 304,
    isbn: "9780441478522",
    tags: ["alien-world", "gender", "identity", "anthropology"]
  },
  {
    id: 78,
    title: "Hyperion",
    author: "Dan Simmons",
    cover: "https://covers.openlibrary.org/b/isbn/9780553283686-L.jpg",
    genre: ["Science Fiction"],
    language: "English",
    year: 1989,
    rating: 4.7,
    description: "Seven pilgrims journey to meet the mysterious Shrike on the planet Hyperion, in a space opera inspired by classical literature.",
    pages: 482,
    isbn: "9780553283686",
    tags: ["space-opera", "pilgrimage", "classics", "complexity"]
  },
  {
    id: 79,
    title: "The Martian",
    author: "Andy Weir",
    cover: "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg",
    genre: ["Science Fiction", "Adventure"],
    language: "English",
    year: 2011,
    rating: 4.4,
    description: "An astronaut stranded on Mars must use his ingenuity and humor to survive and signal for rescue, showcasing human resilience and problem-solving.",
    pages: 369,
    isbn: "9780553418026",
    tags: ["mars", "survival", "space", "humor"]
  },
  {
    id: 80,
    title: "Brave New World",
    author: "Aldous Huxley",
    cover: "https://covers.openlibrary.org/b/isbn/9780060085260-L.jpg",
    genre: ["Science Fiction"],
    language: "English",
    year: 1932,
    rating: 4.3,
    description: "A futuristic dystopia where conditioning, drugs, and pleasure control society, exploring the cost of stability and conformity.",
    pages: 288,
    isbn: "9780060085260",
    tags: ["dystopian", "control", "conformity", "future"]
  },
  {
    id: 81,
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    author: "C.S. Lewis",
    cover: "https://covers.openlibrary.org/b/isbn/9780064471084-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 1950,
    rating: 4.8,
    description: "Children discover a magical wardrobe that leads to the fantasy world of Narnia, where they embark on a quest to defeat an evil witch.",
    pages: 180,
    isbn: "9780064471084",
    tags: ["narnia", "magic", "aslan", "adventure"]
  },
  {
    id: 82,
    title: "The Chronicles of Narnia: Prince Caspian",
    author: "C.S. Lewis",
    cover: "https://covers.openlibrary.org/b/isbn/9780064471077-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 1951,
    rating: 4.5,
    description: "The children return to Narnia to help Prince Caspian reclaim his throne from an usurper, facing battles and moral challenges.",
    pages: 215,
    isbn: "9780064471077",
    tags: ["narnia", "prince", "battle", "throne"]
  },
  {
    id: 83,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    cover: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    year: 1954,
    rating: 4.8,
    description: "A young hobbit inherits a magical ring and must journey across Middle-earth with a fellowship to destroy it before an evil lord finds him.",
    pages: 423,
    isbn: "9780547928227",
    tags: ["hobbit", "ring", "middle-earth", "epic"]
  },
  {
    id: 84,
    title: "The Lord of the Rings: The Two Towers",
    author: "J.R.R. Tolkien",
    cover: "https://covers.openlibrary.org/b/isbn/9780547928234-L.jpg",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    year: 1954,
    rating: 4.8,
    description: "The group is separated as they face mounting dangers, wars, and the continued pursuit of the dark forces.",
    pages: 352,
    isbn: "9780547928234",
    tags: ["middle-earth", "war", "journey", "fantasy"]
  },
  {
    id: 85,
    title: "The Lord of the Rings: The Return of the King",
    author: "J.R.R. Tolkien",
    cover: "https://covers.openlibrary.org/b/isbn/9780547928241-L.jpg",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    year: 1955,
    rating: 4.8,
    description: "The epic conclusion as the final battle approaches and the ring quest reaches its climactic end in Mordor.",
    pages: 416,
    isbn: "9780547928241",
    tags: ["middle-earth", "ring", "victory", "epic"]
  },
  {
    id: 86,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    cover: "https://covers.openlibrary.org/b/isbn/9780747532699-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 1997,
    rating: 4.9,
    description: "A young boy discovers he is a wizard and attends a magical school, making friends and discovering his connection to a dark past.",
    pages: 309,
    isbn: "9780747532699",
    tags: ["wizard", "magic", "school", "friendship"]
  },
  {
    id: 87,
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    cover: "https://covers.openlibrary.org/b/isbn/9780747538493-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 1998,
    rating: 4.8,
    description: "Harry's second year at Hogwarts brings new dangers as a legendary chamber is opened, releasing a monster that petrifies students.",
    pages: 341,
    isbn: "9780747538493",
    tags: ["wizard", "mystery", "school", "danger"]
  },
  {
    id: 88,
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    cover: "https://covers.openlibrary.org/b/isbn/9780747542155-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 1999,
    rating: 4.8,
    description: "An escaped prisoner from Azkaban poses a threat to Harry, while he learns to confront his fears and uncover hidden truths.",
    pages: 317,
    isbn: "9780747542155",
    tags: ["wizard", "escape", "mystery", "dark"]
  },
  {
    id: 89,
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    cover: "https://covers.openlibrary.org/b/isbn/9780747546109-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 2000,
    rating: 4.7,
    description: "Harry is mysteriously selected to compete in a dangerous magical tournament, revealing dark secrets about the world of wizards.",
    pages: 636,
    isbn: "9780747546109",
    tags: ["wizard", "tournament", "magic", "darkness"]
  },
  {
    id: 90,
    title: "Harry Potter and the Order of the Phoenix",
    author: "J.K. Rowling",
    cover: "https://covers.openlibrary.org/b/isbn/9780747551003-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 2003,
    rating: 4.7,
    description: "Harry forms a secret group to teach students magic and combat the rising dark forces threatening the wizarding world.",
    pages: 766,
    isbn: "9780747551003",
    tags: ["wizard", "rebellion", "order", "school"]
  },
  {
    id: 91,
    title: "Harry Potter and the Half-Blood Prince",
    author: "J.K. Rowling",
    cover: "https://covers.openlibrary.org/b/isbn/9780747581109-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 2005,
    rating: 4.7,
    description: "Harry uncovers secrets about his enemy while a mysterious figure guides him, leading to tragic revelations and heartbreak.",
    pages: 607,
    isbn: "9780747581109",
    tags: ["wizard", "secrets", "prince", "tragedy"]
  },
  {
    id: 92,
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    cover: "https://covers.openlibrary.org/b/isbn/9780747591054-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 2007,
    rating: 4.8,
    description: "The epic conclusion as Harry must find and destroy the sources of evil to defeat the dark lord, facing ultimate choices and sacrifice.",
    pages: 759,
    isbn: "9780747591054",
    tags: ["wizard", "final-battle", "sacrifice", "magic"]
  },
  {
    id: 93,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    cover: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    genre: ["Fantasy", "Adventure", "Children"],
    language: "English",
    year: 1937,
    rating: 4.8,
    description: "A small hobbit is swept into an adventure with dwarves and a wizard, embarking on a quest to reclaim treasure from a dragon.",
    pages: 310,
    isbn: "9780547928227",
    tags: ["hobbit", "dragon", "treasure", "middle-earth"]
  },
  {
    id: 94,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    cover: "https://covers.openlibrary.org/b/isbn/9780553103540-L.jpg",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    year: 1996,
    rating: 4.4,
    description: "Multiple noble families vie for control of the Iron Throne in a dark fantasy world filled with political intrigue and danger.",
    pages: 694,
    isbn: "9780553103540",
    tags: ["fantasy", "politics", "warfare", "intrigue"]
  },
  {
    id: 95,
    title: "A Clash of Kings",
    author: "George R.R. Martin",
    cover: "https://covers.openlibrary.org/b/isbn/9780553108032-L.jpg",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    year: 1998,
    rating: 4.4,
    description: "As civil war rages, multiple rulers claim the throne while an ancient evil awakens in the North.",
    pages: 761,
    isbn: "9780553108032",
    tags: ["fantasy", "war", "throne", "intrigue"]
  },
  {
    id: 96,
    title: "A Storm of Swords",
    author: "George R.R. Martin",
    cover: "https://covers.openlibrary.org/b/isbn/9780553106633-L.jpg",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    year: 2000,
    rating: 4.5,
    description: "The war intensifies with shocking betrayals and unexpected alliances as the balance of power shifts dramatically.",
    pages: 973,
    isbn: "9780553106633",
    tags: ["fantasy", "war", "betrayal", "darkness"]
  },
  {
    id: 97,
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    cover: "https://covers.openlibrary.org/b/isbn/9780756404079-L.jpg",
    genre: ["Fantasy"],
    language: "English",
    year: 2007,
    rating: 4.5,
    description: "A legendary figure tells the story of his youth at a magical university while mysterious forces hunt him down.",
    pages: 662,
    isbn: "9780756404079",
    tags: ["magic", "university", "legend", "mystery"]
  },
  {
    id: 98,
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    cover: "https://covers.openlibrary.org/b/isbn/9780765326355-L.jpg",
    genre: ["Fantasy"],
    language: "English",
    year: 2010,
    rating: 4.6,
    description: "An epic fantasy following multiple characters across a richly detailed world on the brink of war and magical transformation.",
    pages: 1007,
    isbn: "9780765326355",
    tags: ["epic", "fantasy", "magic", "war"]
  },
  {
    id: 99,
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    cover: "https://covers.openlibrary.org/b/isbn/9781619631403-L.jpg",
    genre: ["Fantasy"],
    language: "English",
    year: 2015,
    rating: 4.3,
    description: "A human huntress is kidnapped by a faerie and taken to a magical realm, discovering a war and her role in it.",
    pages: 416,
    isbn: "9781619631403",
    tags: ["faerie", "magic", "court", "war"]
  },
  {
    id: 100,
    title: "The Blade Itself",
    author: "Joe Abercrombie",
    cover: "https://covers.openlibrary.org/b/isbn/9780575081406-L.jpg",
    genre: ["Fantasy"],
    language: "English",
    year: 2006,
    rating: 4.4,
    description: "A gritty fantasy following warriors, a soldier, and a torturer as political schemes and warfare threaten their world.",
    pages: 480,
    isbn: "9780575081406",
    tags: ["gritty", "war", "complex", "fantasy"]
  },
  {
    id: 101,
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    cover: "https://covers.openlibrary.org/b/isbn/9780143034902-L.jpg",
    genre: ["Literary Fiction", "Mystery"],
    language: "English",
    year: 2001,
    rating: 4.5,
    description: "A boy discovers a mysterious book in a Barcelona library and becomes obsessed with uncovering the identity of its author.",
    pages: 487,
    isbn: "9780143034902",
    tags: ["mystery", "barcelona", "books", "love"]
  },
  {
    id: 102,
    title: "Things Fall Apart",
    author: "Chinua Achebe",
    cover: "https://covers.openlibrary.org/b/isbn/9780385474542-L.jpg",
    genre: ["Literary Fiction", "Historical Fiction"],
    language: "English",
    year: 1958,
    rating: 4.4,
    description: "A respected Igbo warrior and leader watches his world collapse as European colonizers arrive, disrupting traditional society.",
    pages: 209,
    isbn: "9780385474542",
    tags: ["colonization", "culture", "tragedy", "africa"]
  },
  {
    id: 103,
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    cover: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg",
    genre: ["Literary Fiction"],
    language: "English",
    year: 1967,
    rating: 4.5,
    description: "A multi-generational saga of the Buendía family in the magical town of Macondo, blending reality with myth and wonder.",
    pages: 417,
    isbn: "9780060883287",
    tags: ["magical-realism", "family", "cycles", "wonder"]
  },
  {
    id: 104,
    title: "The Sound and the Fury",
    author: "William Faulkner",
    cover: "https://covers.openlibrary.org/b/isbn/9780679732167-L.jpg",
    genre: ["Literary Fiction"],
    language: "English",
    year: 1929,
    rating: 4.3,
    description: "A fragmented narrative told from multiple perspectives exploring the decay of a Southern family through time and memory.",
    pages: 454,
    isbn: "9780679732167",
    tags: ["family", "decay", "memory", "experimental"]
  },
  {
    id: 105,
    title: "Beloved",
    author: "Toni Morrison",
    cover: "https://covers.openlibrary.org/b/isbn/9781400033416-L.jpg",
    genre: ["Literary Fiction"],
    language: "English",
    year: 1987,
    rating: 4.5,
    description: "An African American woman is haunted by a ghost related to her traumatic past as a slave, exploring themes of memory and motherhood.",
    pages: 324,
    isbn: "9781400033416",
    tags: ["slavery", "memory", "ghosts", "trauma"]
  },
  {
    id: 106,
    title: "Invisible Man",
    author: "Ralph Ellison",
    cover: "https://covers.openlibrary.org/b/isbn/9780140018509-L.jpg",
    genre: ["Literary Fiction"],
    language: "English",
    year: 1952,
    rating: 4.4,
    description: "A nameless African American man narrates his struggle for identity and recognition in mid-20th century America.",
    pages: 581,
    isbn: "9780140018509",
    tags: ["identity", "racism", "society", "struggle"]
  },
  {
    id: 107,
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    cover: "https://covers.openlibrary.org/b/isbn/9780142000640-L.jpg",
    genre: ["Literary Fiction"],
    language: "English",
    year: 1939,
    rating: 4.4,
    description: "During the Great Depression, a family is forced off their farm and travels to California seeking opportunity and survival.",
    pages: 464,
    isbn: "9780142000640",
    tags: ["depression", "family", "struggle", "california"]
  },
  {
    id: 108,
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    cover: "https://covers.openlibrary.org/b/isbn/9780440180296-L.jpg",
    genre: ["Literary Fiction"],
    language: "English",
    year: 1969,
    rating: 4.4,
    description: "A man becomes 'unstuck in time,' experiencing his life non-sequentially, particularly his traumatic experiences in World War II.",
    pages: 275,
    isbn: "9780440180296",
    tags: ["war", "time", "trauma", "absurd"]
  },
  {
    id: 109,
    title: "Catch-22",
    author: "Joseph Heller",
    cover: "https://covers.openlibrary.org/b/isbn/9780684801221-L.jpg",
    genre: ["Literary Fiction"],
    language: "English",
    year: 1961,
    rating: 4.3,
    description: "A dark satire of World War II where military pilots navigate absurd military logic, bureaucracy, and the horrors of war.",
    pages: 575,
    isbn: "9780684801221",
    tags: ["war", "satire", "absurd", "military"]
  },
  {
    id: 110,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    cover: "https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg",
    genre: ["Literary Fiction"],
    language: "English",
    year: 1951,
    rating: 4.2,
    description: "A cynical teenager narrates his brief time in New York City after being expelled from prep school, searching for authenticity.",
    pages: 277,
    isbn: "9780316769174",
    tags: ["coming-of-age", "alienation", "youth", "society"]
  },
  {
    id: 111,
    title: "The Great Gatsby Extended",
    author: "F. Scott Fitzgerald",
    cover: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    genre: ["Literary Fiction", "Classic"],
    language: "English",
    year: 1925,
    rating: 4.3,
    description: "A profound exploration of the American Dream during the Jazz Age with themes of love and wealth.",
    pages: 180,
    isbn: "9780743273565",
    tags: ["american-dream", "wealth", "1920s"]
  },
  {
    id: 112,
    title: "Man's Search for Meaning",
    author: "Viktor Frankl",
    cover: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
    genre: ["Non-Fiction", "Philosophy"],
    language: "English",
    year: 1946,
    rating: 4.7,
    description: "A Holocaust survivor describes his experiences in concentration camps and develops a psychology around finding meaning in all circumstances.",
    pages: 165,
    isbn: "9780807014295",
    tags: ["holocaust", "meaning", "survival", "psychology"]
  },
  {
    id: 113,
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    cover: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    genre: ["Non-Fiction", "Science"],
    language: "English",
    year: 1988,
    rating: 4.3,
    description: "A physicist explains complex concepts of space, time, black holes, and the origins of the universe to a general audience.",
    pages: 198,
    isbn: "9780553380163",
    tags: ["science", "physics", "universe", "cosmology"]
  },
  {
    id: 114,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    cover: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    genre: ["Non-Fiction", "History"],
    language: "English",
    year: 2011,
    rating: 4.5,
    description: "An expansive history of humankind from the Stone Age to the modern era, exploring how societies developed and changed.",
    pages: 443,
    isbn: "9780062316097",
    tags: ["history", "anthropology", "society", "evolution"]
  },
  {
    id: 115,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    cover: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    genre: ["Non-Fiction", "Psychology"],
    language: "English",
    year: 2011,
    rating: 4.4,
    description: "A Nobel Prize-winning psychologist explores how our minds make decisions through fast intuition and slow rational thinking.",
    pages: 499,
    isbn: "9780374533557",
    tags: ["psychology", "decision-making", "cognition"]
  },
  {
    id: 116,
    title: "Educated",
    author: "Tara Westover",
    cover: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    genre: ["Non-Fiction", "Biography"],
    language: "English",
    year: 2018,
    rating: 4.7,
    description: "A woman raised by survivalists with no formal education escapes to pursue higher learning, discovering her own identity.",
    pages: 352,
    isbn: "9780399590504",
    tags: ["autobiography", "education", "family", "survival"]
  },
  {
    id: 117,
    title: "Becoming",
    author: "Michelle Obama",
    cover: "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
    genre: ["Non-Fiction", "Biography"],
    language: "English",
    year: 2018,
    rating: 4.6,
    description: "The former First Lady shares her journey from Chicago to the White House, reflecting on family, identity, and purpose.",
    pages: 426,
    isbn: "9781524763138",
    tags: ["autobiography", "memoir", "politics", "inspiration"]
  },
  {
    id: 118,
    title: "Outliers",
    author: "Malcolm Gladwell",
    cover: "https://covers.openlibrary.org/b/isbn/9780316017923-L.jpg",
    genre: ["Non-Fiction", "Psychology"],
    language: "English",
    year: 2008,
    rating: 4.3,
    description: "An exploration of what makes people successful, from the '10,000-hour rule' to cultural advantages and hidden factors.",
    pages: 309,
    isbn: "9780316017923",
    tags: ["success", "psychology", "analysis", "motivation"]
  },
  {
    id: 119,
    title: "Into the Wild",
    author: "Jon Krakauer",
    cover: "https://covers.openlibrary.org/b/isbn/9780385486805-L.jpg",
    genre: ["Non-Fiction", "Biography"],
    language: "English",
    year: 1996,
    rating: 4.4,
    description: "The true story of a young man who walks into the wilderness of Alaska to find freedom, ultimately dying in the harsh environment.",
    pages: 207,
    isbn: "9780385486805",
    tags: ["wilderness", "tragedy", "nature", "freedom"]
  },
  {
    id: 120,
    title: "I Know Why the Caged Bird Sings",
    author: "Maya Angelou",
    cover: "https://covers.openlibrary.org/b/isbn/9780553386936-L.jpg",
    genre: ["Non-Fiction", "Biography"],
    language: "English",
    year: 1969,
    rating: 4.5,
    description: "An autobiography of resilience as a woman overcomes trauma, racism, and personal hardship to find her voice and power.",
    pages: 246,
    isbn: "9780553386936",
    tags: ["memoir", "resilience", "voice", "identity"]
  },
  {
    id: 121,
    title: "Mindset",
    author: "Carol S. Dweck",
    cover: "https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg",
    genre: ["Self-Help", "Psychology"],
    language: "English",
    year: 2006,
    rating: 4.4,
    description: "A groundbreaking exploration of how a fixed mindset can limit growth, while a growth mindset can unlock potential.",
    pages: 276,
    isbn: "9780345472328",
    tags: ["mindset", "psychology", "growth", "success"]
  },
  {
    id: 122,
    title: "The Power of Now",
    author: "Eckhart Tolle",
    cover: "https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg",
    genre: ["Self-Help", "Philosophy"],
    language: "English",
    year: 1997,
    rating: 4.3,
    description: "A guide to living in the present moment and overcoming ego-based thinking to achieve spiritual awakening.",
    pages: 236,
    isbn: "9781577314806",
    tags: ["spirituality", "mindfulness", "philosophy"]
  },
  {
    id: 123,
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen Covey",
    cover: "https://covers.openlibrary.org/b/isbn/9780671663285-L.jpg",
    genre: ["Self-Help", "Business"],
    language: "English",
    year: 1989,
    rating: 4.4,
    description: "A framework for personal development based on principles of character, integrity, and alignment with personal mission.",
    pages: 372,
    isbn: "9780671663285",
    tags: ["habits", "effectiveness", "leadership", "character"]
  },
  {
    id: 124,
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    cover: "https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg",
    genre: ["Self-Help", "Business"],
    language: "English",
    year: 1936,
    rating: 4.4,
    description: "A classic guide to improving relationships, communication, and influence through empathy and genuine interest in others.",
    pages: 291,
    isbn: "9780671027032",
    tags: ["relationships", "communication", "influence"]
  },
  {
    id: 125,
    title: "Atomic Habits",
    author: "James Clear",
    cover: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    genre: ["Self-Help"],
    language: "English",
    year: 2018,
    rating: 4.5,
    description: "A practical guide to building better habits through small, incremental changes that compound over time.",
    pages: 320,
    isbn: "9780735211292",
    tags: ["habits", "improvement", "behavior", "success"]
  },
  {
    id: 126,
    title: "Deep Work",
    author: "Cal Newport",
    cover: "https://covers.openlibrary.org/b/isbn/9780465062706-L.jpg",
    genre: ["Self-Help", "Business"],
    language: "English",
    year: 2016,
    rating: 4.4,
    description: "A guide to focusing on cognitively demanding tasks in a world of distractions, maximizing productivity and impact.",
    pages: 296,
    isbn: "9780465062706",
    tags: ["focus", "productivity", "work", "distraction"]
  },
  {
    id: 127,
    title: "The Lean Startup",
    author: "Eric Ries",
    cover: "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
    genre: ["Business"],
    language: "English",
    year: 2011,
    rating: 4.3,
    description: "A methodology for building businesses through rapid experimentation, feedback, and iterative product development.",
    pages: 299,
    isbn: "9780307887894",
    tags: ["startup", "business", "innovation", "lean"]
  },
  {
    id: 128,
    title: "Zero to One",
    author: "Peter Thiel",
    cover: "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
    genre: ["Business"],
    language: "English",
    year: 2014,
    rating: 4.4,
    description: "An exploration of how to build innovative businesses that create new markets rather than competing in existing ones.",
    pages: 210,
    isbn: "9780804139298",
    tags: ["innovation", "startup", "competition", "business"]
  },
  {
    id: 129,
    title: "Thinking, Fast and Slow Extended",
    author: "Daniel Kahneman",
    cover: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    genre: ["Business", "Psychology"],
    language: "English",
    year: 2011,
    rating: 4.4,
    description: "Further exploration of behavioral economics and how understanding thinking patterns leads to better decisions.",
    pages: 499,
    isbn: "9780374533557",
    tags: ["economics", "behavior", "decision-making"]
  },
  {
    id: 130,
    title: "The Goal",
    author: "Eliyahu M. Goldratt",
    cover: "https://covers.openlibrary.org/b/isbn/9780884271529-L.jpg",
    genre: ["Business", "Fiction"],
    language: "English",
    year: 1984,
    rating: 4.4,
    description: "A business novel about optimizing manufacturing processes through the Theory of Constraints.",
    pages: 418,
    isbn: "9780884271529",
    tags: ["business", "optimization", "theory-of-constraints"]
  },
  {
    id: 131,
    title: "A Brief History of Humankind",
    author: "Yuval Noah Harari",
    cover: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    genre: ["History", "Science"],
    language: "English",
    year: 2014,
    rating: 4.4,
    description: "An overview of key developments in human history from cognitive revolution to the present.",
    pages: 443,
    isbn: "9780062316097",
    tags: ["history", "science", "evolution", "society"]
  },
  {
    id: 132,
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    cover: "https://covers.openlibrary.org/b/isbn/9780199291151-L.jpg",
    genre: ["Science"],
    language: "English",
    year: 1976,
    rating: 4.3,
    description: "A revolutionary perspective on evolution proposing that genes, not organisms, are the primary drivers of natural selection.",
    pages: 224,
    isbn: "9780199291151",
    tags: ["evolution", "biology", "genetics", "science"]
  },
  {
    id: 133,
    title: "Cosmos",
    author: "Carl Sagan",
    cover: "https://covers.openlibrary.org/b/isbn/9780394503677-L.jpg",
    genre: ["Science", "Non-Fiction"],
    language: "English",
    year: 1980,
    rating: 4.6,
    description: "A sweeping journey through space and time, exploring the universe, life, and humanity's place in the cosmos.",
    pages: 365,
    isbn: "9780394503677",
    tags: ["astronomy", "science", "universe", "wonder"]
  },
  {
    id: 134,
    title: "The Double Helix",
    author: "James Watson",
    cover: "https://covers.openlibrary.org/b/isbn/9780760754550-L.jpg",
    genre: ["Science", "Non-Fiction"],
    language: "English",
    year: 1968,
    rating: 4.3,
    description: "A firsthand account of the discovery of DNA's structure, revealing the personal drama behind scientific achievement.",
    pages: 226,
    isbn: "9780760754550",
    tags: ["dna", "science", "discovery", "biography"]
  },
  {
    id: 135,
    title: "On the Origin of Species",
    author: "Charles Darwin",
    cover: "https://covers.openlibrary.org/b/isbn/9780140439006-L.jpg",
    genre: ["Science", "Non-Fiction"],
    language: "English",
    year: 1859,
    rating: 4.4,
    description: "Darwin's groundbreaking work introducing the theory of evolution through natural selection, revolutionizing biological science.",
    pages: 576,
    isbn: "9780140439006",
    tags: ["evolution", "science", "biology", "theory"]
  },
  {
    id: 136,
    title: "The Structure of Scientific Revolutions",
    author: "Thomas Kuhn",
    cover: "https://covers.openlibrary.org/b/isbn/9780226457819-L.jpg",
    genre: ["Philosophy", "Science"],
    language: "English",
    year: 1962,
    rating: 4.3,
    description: "An analysis of how scientific fields progress through paradigm shifts rather than gradual accumulation of knowledge.",
    pages: 212,
    isbn: "9780226457819",
    tags: ["philosophy", "science", "paradigm", "revolution"]
  },
  {
    id: 137,
    title: "A Critique of Pure Reason",
    author: "Immanuel Kant",
    cover: "https://covers.openlibrary.org/b/isbn/9780140447453-L.jpg",
    genre: ["Philosophy"],
    language: "English",
    year: 1781,
    rating: 3.8,
    description: "Kant's foundational work exploring the nature of knowledge, reality, and the limits of human reason.",
    pages: 688,
    isbn: "9780140447453",
    tags: ["philosophy", "reason", "knowledge", "metaphysics"]
  },
  {
    id: 138,
    title: "Meditations",
    author: "Marcus Aurelius",
    cover: "https://covers.openlibrary.org/b/isbn/9780140449334-L.jpg",
    genre: ["Philosophy", "Non-Fiction"],
    language: "English",
    year: 170,
    rating: 4.5,
    description: "A collection of personal writings by a Roman emperor reflecting on Stoic philosophy and virtue.",
    pages: 304,
    isbn: "9780140449334",
    tags: ["stoicism", "philosophy", "virtue", "wisdom"]
  },
  {
    id: 139,
    title: "The Phenomenology of Spirit",
    author: "Georg Wilhelm Friedrich Hegel",
    cover: "https://covers.openlibrary.org/b/isbn/9780198245019-L.jpg",
    genre: ["Philosophy"],
    language: "English",
    year: 1807,
    rating: 3.7,
    description: "Hegel's complex exploration of consciousness, history, and the development of human understanding.",
    pages: 678,
    isbn: "9780198245019",
    tags: ["philosophy", "consciousness", "history", "dialectic"]
  },
  {
    id: 140,
    title: "Being and Nothingness",
    author: "Jean-Paul Sartre",
    cover: "https://covers.openlibrary.org/b/isbn/9780415267915-L.jpg",
    genre: ["Philosophy"],
    language: "English",
    year: 1943,
    rating: 4.0,
    description: "Sartre's existentialist philosophy exploring freedom, consciousness, and the nature of human existence.",
    pages: 799,
    isbn: "9780415267915",
    tags: ["existentialism", "philosophy", "freedom", "consciousness"]
  },
  {
    id: 141,
    title: "Walkabout",
    author: "James Vance Marshall",
    cover: "https://covers.openlibrary.org/b/isbn/9781580080872-L.jpg",
    genre: ["Adventure", "Non-Fiction"],
    language: "English",
    year: 1959,
    rating: 4.2,
    description: "A gripping survival story of two children lost in the Australian Outback who are helped by an Aboriginal boy.",
    pages: 182,
    isbn: "9781580080872",
    tags: ["survival", "outback", "adventure", "culture"]
  },
  {
    id: 142,
    title: "The Blue Highway",
    author: "William Least Heat-Moon",
    cover: "https://covers.openlibrary.org/b/isbn/9780316353960-L.jpg",
    genre: ["Travel", "Non-Fiction"],
    language: "English",
    year: 1982,
    rating: 4.4,
    description: "A traveler journeys across backroads of America in a van, documenting stories and wisdom of people met.",
    pages: 416,
    isbn: "9780316353960",
    tags: ["road-trip", "travels", "backroads", "america"]
  },
  {
    id: 143,
    title: "In A Sunburned Country",
    author: "Bill Bryson",
    cover: "https://covers.openlibrary.org/b/isbn/9780767903868-L.jpg",
    genre: ["Travel", "Non-Fiction"],
    language: "English",
    year: 2000,
    rating: 4.6,
    description: "A humorous travelogue across Australia describing unique geography, wildlife, and people.",
    pages: 352,
    isbn: "9780767903868",
    tags: ["humor", "travelogue", "australia", "adventure"]
  },
  {
    id: 144,
    title: "A Walk in the Woods",
    author: "Bill Bryson",
    cover: "https://covers.openlibrary.org/b/isbn/9780307279460-L.jpg",
    genre: ["Travel", "Non-Fiction", "Adventure"],
    language: "English",
    year: 1998,
    rating: 4.6,
    description: "The account of two friends hiking the Appalachian Trail, exploring history and ecology.",
    pages: 397,
    isbn: "9780307279460",
    tags: ["hiking", "appalachian-trail", "humor", "woods"]
  },
  {
    id: 145,
    title: "Notes from a Small Island",
    author: "Bill Bryson",
    cover: "https://covers.openlibrary.org/b/isbn/9780380727506-L.jpg",
    genre: ["Travel", "Non-Fiction"],
    language: "English",
    year: 1995,
    rating: 4.5,
    description: "A humorous travelogue celebrating the culture, transport, and landscapes of Great Britain.",
    pages: 324,
    isbn: "9780380727506",
    tags: ["humor", "travels", "britain", "island"]
  },
  {
    id: 146,
    title: "Neither Here nor There",
    author: "Bill Bryson",
    cover: "https://covers.openlibrary.org/b/isbn/9780380713806-L.jpg",
    genre: ["Travel", "Non-Fiction"],
    language: "English",
    year: 1991,
    rating: 4.4,
    description: "Bryson travels across Europe sharing amusing travel memories and cultural observations.",
    pages: 254,
    isbn: "9780380713806",
    tags: ["humor", "europe", "travels", "memories"]
  },
  {
    id: 147,
    title: "The Road to Little Dribbling",
    author: "Bill Bryson",
    cover: "https://covers.openlibrary.org/b/isbn/9780385352697-L.jpg",
    genre: ["Travel", "Non-Fiction"],
    language: "English",
    year: 2015,
    rating: 4.4,
    description: "Twenty years after famous travels, Bill Bryson journeys across Great Britain again with cultural insights.",
    pages: 400,
    isbn: "9780385352697",
    tags: ["humor", "britain", "returns", "travels"]
  },
  {
    id: 148,
    title: "A Short History of Nearly Everything",
    author: "Bill Bryson",
    cover: "https://covers.openlibrary.org/b/isbn/9780767908184-L.jpg",
    genre: ["Non-Fiction", "Science"],
    language: "English",
    year: 2003,
    rating: 4.7,
    description: "Bill Bryson makes the history of science from the big bang to civilization highly accessible.",
    pages: 544,
    isbn: "9780767908184",
    tags: ["science-history", "astronomy", "geology", "humor"]
  },
  {
    id: 149,
    title: "The Body: A Guide for Occupants",
    author: "Bill Bryson",
    cover: "https://covers.openlibrary.org/b/isbn/9780385539913-L.jpg",
    genre: ["Non-Fiction", "Science"],
    language: "English",
    year: 2019,
    rating: 4.6,
    description: "A fascinating exploration of how the human body works, heals, and functions with humor.",
    pages: 450,
    isbn: "9780385539913",
    tags: ["body", "biology", "health", "humor"]
  },
  {
    id: 150,
    title: "One Summer: America 1927",
    author: "Bill Bryson",
    cover: "https://covers.openlibrary.org/b/isbn/9780767919401-L.jpg",
    genre: ["Non-Fiction", "History"],
    language: "English",
    year: 2013,
    rating: 4.5,
    description: "A chronicle of a pivotal summer in American history with Lindbergh, Babe Ruth, and the roaring twenties.",
    pages: 528,
    isbn: "9780767919401",
    tags: ["history", "summer", "1927", "america"]
  },
  {
    id: 151,
    title: "Selected Poems",
    author: "Emily Dickinson",
    cover: "https://covers.openlibrary.org/b/isbn/9780553211184-L.jpg",
    genre: ["Poetry", "Classic"],
    language: "English",
    year: 1890,
    rating: 4.6,
    description: "A collection of profound and deeply contemplative poems exploring themes of nature and life.",
    pages: 120,
    isbn: "9780553211184",
    tags: ["poetry", "contemplation", "nature", "classic"]
  },
  {
    id: 152,
    title: "Selected Poetry",
    author: "William Wordsworth",
    cover: "https://covers.openlibrary.org/b/isbn/9780140424423-L.jpg",
    genre: ["Poetry", "Classic"],
    language: "English",
    year: 1807,
    rating: 4.5,
    description: "A collection of celebrated nature poetry from a pioneer of the Romantic movement.",
    pages: 320,
    isbn: "9780140424423",
    tags: ["poetry", "nature", "romanticism", "classic"]
  },
  {
    id: 153,
    title: "The Prophet",
    author: "Kahlil Gibran",
    cover: "https://covers.openlibrary.org/b/isbn/9780394404288-L.jpg",
    genre: ["Poetry", "Philosophy"],
    language: "English",
    year: 1923,
    rating: 4.7,
    description: "Twenty-six beautiful poetic essays offering philosophical reflections on love, marriage, work, and sorrow.",
    pages: 96,
    isbn: "9780394404288",
    tags: ["essays", "poetry", "philosophy", "wisdom"]
  },
  {
    id: 154,
    title: "Selected Poems",
    author: "Robert Frost",
    cover: "https://covers.openlibrary.org/b/isbn/9780805069860-L.jpg",
    genre: ["Poetry", "Classic"],
    language: "English",
    year: 1923,
    rating: 4.7,
    description: "A collection of beloved classic poems including 'The Road Not Taken' and 'Stopping by Woods on a Snowy Evening'.",
    pages: 144,
    isbn: "9780805069860",
    tags: ["poetry", "rural", "choices", "nature"]
  },
  {
    id: 155,
    title: "Devotions",
    author: "Mary Oliver",
    cover: "https://covers.openlibrary.org/b/isbn/9780399563249-L.jpg",
    genre: ["Poetry", "Non-Fiction"],
    language: "English",
    year: 2017,
    rating: 4.8,
    description: "A comprehensive collection of Mary Oliver's celebrated nature poetry observing quiet wonder.",
    pages: 464,
    isbn: "9780399563249",
    tags: ["poetry", "nature", "wonder", "mindfulness"]
  },
  {
    id: 156,
    title: "A Gentle Reminder",
    author: "Bianca Sparacino",
    cover: "https://covers.openlibrary.org/b/isbn/9781949759297-L.jpg",
    genre: ["Poetry", "Self-Help"],
    language: "English",
    year: 2020,
    rating: 4.6,
    description: "Gentle reminders and poetic prose encouraging self-love and finding peace.",
    pages: 150,
    isbn: "9781949759297",
    tags: ["poetry", "healing", "patience", "self-love"]
  },
  {
    id: 157,
    title: "Home Body",
    author: "Rupi Kaur",
    cover: "https://covers.openlibrary.org/b/isbn/9781449486808-L.jpg",
    genre: ["Poetry", "Contemporary Fiction"],
    language: "English",
    year: 2020,
    rating: 4.4,
    description: "A collection of short illustrated poems reflecting on self-love and acceptance.",
    pages: 256,
    isbn: "9781449486808",
    tags: ["poetry", "illustrations", "acceptance", "growth"]
  },
  {
    id: 158,
    title: "Milk and Honey",
    author: "Rupi Kaur",
    cover: "https://covers.openlibrary.org/b/isbn/9781449474256-L.jpg",
    genre: ["Poetry", "Contemporary Fiction"],
    language: "English",
    year: 2014,
    rating: 4.3,
    description: "A collection of poetry and prose about survival, healing, and growth.",
    pages: 204,
    isbn: "9781449474256",
    tags: ["poetry", "healing", "survival", "modern"]
  },
  {
    id: 159,
    title: "The Sun and Her Flowers",
    author: "Rupi Kaur",
    cover: "https://covers.openlibrary.org/b/isbn/9781449486792-L.jpg",
    genre: ["Poetry", "Contemporary Fiction"],
    language: "English",
    year: 2017,
    rating: 4.4,
    description: "A vibrant journey exploring growth through five chapters of transformation.",
    pages: 256,
    isbn: "9781449486792",
    tags: ["poetry", "growth", "blooming", "healing"]
  },
  {
    id: 160,
    title: "Sea of Strangers",
    author: "Lang Leav",
    cover: "https://covers.openlibrary.org/b/isbn/9781449489397-L.jpg",
    genre: ["Poetry", "Contemporary Fiction"],
    language: "English",
    year: 2018,
    rating: 4.3,
    description: "A collection of poetry exploring themes of loss, self-discovery, and quiet moments.",
    pages: 224,
    isbn: "9781449489397",
    tags: ["poetry", "loss", "discovery", "reflections"]
  },
  {
    id: 161,
    title: "Lullabies",
    author: "Lang Leav",
    cover: "https://covers.openlibrary.org/b/isbn/9781449461072-L.jpg",
    genre: ["Poetry", "Contemporary Fiction"],
    language: "English",
    year: 2014,
    rating: 4.4,
    description: "A musical collection of poetry exploring rhythms and sweet verses.",
    pages: 240,
    isbn: "9781449461072",
    tags: ["poetry", "rhythms", "sweet"]
  },
  {
    id: 162,
    title: "Love & Misadventure",
    author: "Lang Leav",
    cover: "https://covers.openlibrary.org/b/isbn/9781449456146-L.jpg",
    genre: ["Poetry", "Contemporary Fiction"],
    language: "English",
    year: 2013,
    rating: 4.3,
    description: "Lang Leav's debut collection offering whimsical and beautifully simple verses.",
    pages: 176,
    isbn: "9781449456146",
    tags: ["poetry", "whimsical"]
  },
  {
    id: 163,
    title: "Leaves of Grass",
    author: "Walt Whitman",
    cover: "https://covers.openlibrary.org/b/isbn/9780451528438-L.jpg",
    genre: ["Poetry", "Classic"],
    language: "English",
    year: 1855,
    rating: 4.5,
    description: "A celebration of humanity and nature in Walt Whitman's landmark American poetry.",
    pages: 464,
    isbn: "9780451528438",
    tags: ["democracy", "nature", "humanity", "expression"]
  },
  {
    id: 164,
    title: "Pillow Thoughts",
    author: "Courtney Peppernell",
    cover: "https://covers.openlibrary.org/b/isbn/9781449489755-L.jpg",
    genre: ["Poetry", "Self-Help"],
    language: "English",
    year: 2017,
    rating: 4.3,
    description: "A collection of modern poetry for different feelings offering comfort.",
    pages: 272,
    isbn: "9781449489755",
    tags: ["poetry", "feelings", "nights", "comfort"]
  },
  {
    id: 165,
    title: "The Rose That Grew From Concrete",
    author: "Tupac Shakur",
    cover: "https://covers.openlibrary.org/b/isbn/9780671028459-L.jpg",
    genre: ["Poetry", "Non-Fiction"],
    language: "English",
    year: 1999,
    rating: 4.6,
    description: "A collection of personal and moving early poems exploring hope and struggle.",
    pages: 176,
    isbn: "9780671028459",
    tags: ["hope", "honesty", "struggle", "poems"]
  },
  {
    id: 166,
    title: "Teaching My Mother How to Give Birth",
    author: "Warsan Shire",
    cover: "https://covers.openlibrary.org/b/isbn/9780956562562-L.jpg",
    genre: ["Poetry", "Literary Fiction"],
    language: "English",
    year: 2011,
    rating: 4.5,
    description: "Powerful poetry exploring displacement and the journey of home.",
    pages: 38,
    isbn: "9780956562562",
    tags: ["poetry", "home", "family", "displacement"]
  },
  {
    id: 167,
    title: "The Hill We Climb",
    author: "Amanda Gorman",
    cover: "https://covers.openlibrary.org/b/isbn/9780593465271-L.jpg",
    genre: ["Poetry", "Non-Fiction"],
    language: "English",
    year: 2021,
    rating: 4.8,
    description: "The inspiring inaugural poem calling for unity, hope, and progress.",
    pages: 32,
    isbn: "9780593465271",
    tags: ["inauguration", "progress", "unity", "hope"]
  },
  {
    id: 168,
    title: "Twenty Thousand Leagues Under the Seas",
    author: "Jules Verne",
    cover: "https://covers.openlibrary.org/b/isbn/9780141321059-L.jpg",
    genre: ["Classic", "Adventure", "Science Fiction"],
    language: "English",
    year: 1870,
    rating: 4.6,
    description: "Companions are captured aboard the Nautilus by Captain Nemo for a grand oceanic tour.",
    pages: 432,
    isbn: "9780141321059",
    tags: ["nautilus", "nemo", "ocean", "classic"]
  },
  {
    id: 169,
    title: "Around the World in Eighty Days",
    author: "Jules Verne",
    cover: "https://covers.openlibrary.org/b/isbn/9780142001110-L.jpg",
    genre: ["Classic", "Adventure"],
    language: "English",
    year: 1872,
    rating: 4.5,
    description: "An eccentric gentleman bets he can circumnavigate the globe in eighty days.",
    pages: 288,
    isbn: "9780142001110",
    tags: ["journey", "race", "fogg", "adventure"]
  },
  {
    id: 170,
    title: "Journey to the Center of the Earth",
    author: "Jules Verne",
    cover: "https://covers.openlibrary.org/b/isbn/9780141441979-L.jpg",
    genre: ["Classic", "Adventure", "Science Fiction"],
    language: "English",
    year: 1864,
    rating: 4.4,
    description: "An expedition descends into an Icelandic volcano discovering a wondrous subterranean world.",
    pages: 304,
    isbn: "9780141441979",
    tags: ["volcano", "prehistoric", "journey", "classic"]
  },
  {
    id: 171,
    title: "The Lost World",
    author: "Arthur Conan Doyle",
    cover: "https://covers.openlibrary.org/b/isbn/9780140437072-L.jpg",
    genre: ["Classic", "Adventure", "Science Fiction"],
    language: "English",
    year: 1912,
    rating: 4.5,
    description: "An expedition to a remote plateau where prehistoric creatures still survive.",
    pages: 240,
    isbn: "9780140437072",
    tags: ["dinosaurs", "plateau", "expedition", "challenger"]
  },
  {
    id: 172,
    title: "The War of the Worlds",
    author: "H.G. Wells",
    cover: "https://covers.openlibrary.org/b/isbn/9780451528575-L.jpg",
    genre: ["Classic", "Science Fiction", "Adventure"],
    language: "English",
    year: 1898,
    rating: 4.5,
    description: "A landmark science fiction depicting an invasion of Earth by advanced Martian machines.",
    pages: 208,
    isbn: "9780451528575",
    tags: ["aliens", "invasion", "martians", "survival"]
  },
  {
    id: 173,
    title: "Pollyanna",
    author: "Eleanor H. Porter",
    cover: "https://covers.openlibrary.org/b/isbn/9780140368598-L.jpg",
    genre: ["Classic", "Children", "Fiction"],
    language: "English",
    year: 1913,
    rating: 4.6,
    description: "An orphan teaches a town her 'glad game' of finding something to be glad about.",
    pages: 224,
    isbn: "9780140368598",
    tags: ["optimism", "gladness", "healing", "family"]
  },
  {
    id: 174,
    title: "The Wonderful Wizard of Oz",
    author: "L. Frank Baum",
    cover: "https://covers.openlibrary.org/b/isbn/9780199540600-L.jpg",
    genre: ["Classic", "Fantasy", "Children"],
    language: "English",
    year: 1900,
    rating: 4.7,
    description: "Dorothy and Toto are swept by a cyclone to the magical Land of Oz.",
    pages: 144,
    isbn: "9780199540600",
    tags: ["emerald-city", "scarecrow", "dorothy", "magic"]
  },
  {
    id: 175,
    title: "Rebecca of Sunnybrook Farm",
    author: "Kate Douglas Wiggin",
    cover: "https://covers.openlibrary.org/b/isbn/9780140368635-L.jpg",
    genre: ["Classic", "Children", "Fiction"],
    language: "English",
    year: 1903,
    rating: 4.5,
    description: "A clever girl goes to live with strict aunts, winning over the town with her warmth.",
    pages: 256,
    isbn: "9780140368635",
    tags: ["family", "imagination", "growth", "maine"]
  },
  {
    id: 176,
    title: "The Call of the Wild",
    author: "Jack London",
    cover: "https://covers.openlibrary.org/b/isbn/9780141321028-L.jpg",
    genre: ["Classic", "Adventure", "Children"],
    language: "English",
    year: 1903,
    rating: 4.6,
    description: "A pet dog is sold as a sled dog during the Klondike Gold Rush, discovering his wild nature.",
    pages: 172,
    isbn: "9780141321028",
    tags: ["dog", "yukon", "gold-rush", "nature"]
  },
  {
    id: 177,
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg",
    genre: ["Classic", "Fantasy", "Children"],
    language: "English",
    year: 1865,
    rating: 4.7,
    description: "A young girl falls down a rabbit hole into a whimsical fantasy world.",
    pages: 192,
    isbn: "9780141439761",
    tags: ["wonderland", "rabbit-hole", "whimsical", "classic"]
  },
  {
    id: 178,
    title: "Through the Looking-Glass",
    author: "Lewis Carroll",
    cover: "https://covers.openlibrary.org/b/isbn/9780141439761-L.jpg",
    genre: ["Classic", "Fantasy", "Children"],
    language: "English",
    year: 1871,
    rating: 4.6,
    description: "Alice enters a fantastical world through a mirror structured as a giant chess game.",
    pages: 224,
    isbn: "9780141439761",
    tags: ["looking-glass", "mirror", "chess", "classic"]
  },
  {
    id: 179,
    title: "The Wind in the Willows",
    author: "Kenneth Grahame",
    cover: "https://covers.openlibrary.org/b/isbn/9780143039044-L.jpg",
    genre: ["Classic", "Adventure", "Children"],
    language: "English",
    year: 1908,
    rating: 4.6,
    description: "The lives and delightful adventures of four anthropomorphized animals along a riverbank.",
    pages: 256,
    isbn: "9780143039044",
    tags: ["riverbank", "animals", "toad", "friendship"]
  },
  {
    id: 180,
    title: "The Secret of the Old Clock",
    author: "Carolyn Keene",
    cover: "https://covers.openlibrary.org/b/isbn/9780448095011-L.jpg",
    genre: ["Mystery", "Children"],
    language: "English",
    year: 1930,
    rating: 4.5,
    description: "Teen detective Nancy Drew solves her first case uncovering a hidden will.",
    pages: 180,
    isbn: "9780448095011",
    tags: ["nancy-drew", "first-case", "will", "mystery"]
  },
  {
    id: 181,
    title: "The Tower Treasure",
    author: "Franklin W. Dixon",
    cover: "https://covers.openlibrary.org/b/isbn/9780448089010-L.jpg",
    genre: ["Mystery", "Children"],
    language: "English",
    year: 1927,
    rating: 4.4,
    description: "The first Hardy Boys mystery investigating a major robbery.",
    pages: 180,
    isbn: "9780448089010",
    tags: ["hardy-boys", "robbery", "mansion", "first-case"]
  },
  {
    id: 182,
    title: "The Chronicles of Narnia: The Silver Chair",
    author: "C.S. Lewis",
    cover: "https://covers.openlibrary.org/b/isbn/9780064471091-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 1953,
    rating: 4.6,
    description: "Two sent to find the missing Prince Rilian, heir of King Caspian.",
    pages: 243,
    isbn: "9780064471091",
    tags: ["prince", "quest", "narnia", "courage"]
  },
  {
    id: 183,
    title: "The Chronicles of Narnia: The Last Battle",
    author: "C.S. Lewis",
    cover: "https://covers.openlibrary.org/b/isbn/9780064471084-L.jpg",
    genre: ["Fantasy", "Children", "Adventure"],
    language: "English",
    year: 1956,
    rating: 4.5,
    description: "The epic conclusion to the Chronicles of Narnia.",
    pages: 224,
    isbn: "9780064471084",
    tags: ["narnia", "conclusion", "aslan", "battle"]
  },
  {
    id: 184,
    title: "Black Beauty",
    author: "Anna Sewell",
    cover: "https://covers.openlibrary.org/b/isbn/9780141321035-L.jpg",
    genre: ["Classic", "Children", "Fiction"],
    language: "English",
    year: 1877,
    rating: 4.6,
    description: "A horse narrates his life story spreading a message of kindness to all animals.",
    pages: 256,
    isbn: "9780141321035",
    tags: ["horse", "kindness", "animals", "classic"]
  },
  {
    id: 185,
    title: "Heidi",
    author: "Johanna Spyri",
    cover: "https://covers.openlibrary.org/b/isbn/9780141322568-L.jpg",
    genre: ["Classic", "Children", "Fiction"],
    language: "English",
    year: 1881,
    rating: 4.7,
    description: "An orphan is sent to live with her grandfather in the Swiss Alps.",
    pages: 352,
    isbn: "9780141322568",
    tags: ["alps", "mountain", "friendship", "healing"]
  },
  {
    id: 186,
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    cover: "https://covers.openlibrary.org/b/isbn/9780141321011-L.jpg",
    genre: ["Classic", "Adventure", "Children"],
    language: "English",
    year: 1883,
    rating: 4.6,
    description: "Young Jim Hawkins finds a treasure map and embarks on a dangerous voyage.",
    pages: 240,
    isbn: "9780141321011",
    tags: ["pirates", "treasure", "sea", "adventure"]
  },
  {
    id: 187,
    title: "The Railway Children",
    author: "E. Nesbit",
    cover: "https://covers.openlibrary.org/b/isbn/9780141321608-L.jpg",
    genre: ["Classic", "Children", "Fiction"],
    language: "English",
    year: 1906,
    rating: 4.5,
    description: "Three children discover adventures near a railway line after their father is falsely accused.",
    pages: 272,
    isbn: "9780141321608",
    tags: ["railway", "family", "hope", "kindness"]
  },
  {
    id: 188,
    title: "Peter Pan",
    author: "J.M. Barrie",
    cover: "https://covers.openlibrary.org/b/isbn/9780141322575-L.jpg",
    genre: ["Classic", "Children", "Fantasy"],
    language: "English",
    year: 1911,
    rating: 4.7,
    description: "Peter Pan takes children to the magical island of Neverland for unforgettable adventures.",
    pages: 240,
    isbn: "9780141322575",
    tags: ["neverland", "magic", "peter-pan", "wendy"]
  },
  {
    id: 189,
    title: "Anne of Green Gables",
    author: "L.M. Montgomery",
    cover: "https://covers.openlibrary.org/b/isbn/9780141321394-L.jpg",
    genre: ["Classic", "Children", "Fiction"],
    language: "English",
    year: 1908,
    rating: 4.8,
    description: "An imaginative orphan girl is sent by mistake, transforming lives and a town.",
    pages: 382,
    isbn: "9780141321394",
    tags: ["anne", "prince-edward-island", "imagination", "family"]
  },
  {
    id: 190,
    title: "Anne of Avonlea",
    author: "L.M. Montgomery",
    cover: "https://covers.openlibrary.org/b/isbn/9780141321400-L.jpg",
    genre: ["Classic", "Children", "Fiction"],
    language: "English",
    year: 1909,
    rating: 4.6,
    description: "Anne begins her career as a schoolteacher continuing her adventures.",
    pages: 288,
    isbn: "9780141321400",
    tags: ["teacher", "avonlea", "growth", "classic"]
  },
  {
    id: 191,
    title: "The Swiss Family Robinson",
    author: "Johann David Wyss",
    cover: "https://covers.openlibrary.org/b/isbn/9780141321042-L.jpg",
    genre: ["Classic", "Adventure", "Children"],
    language: "English",
    year: 1812,
    rating: 4.5,
    description: "A Swiss family is shipwrecked on a remote tropical island building a marvelous home.",
    pages: 384,
    isbn: "9780141321042",
    tags: ["shipwreck", "island", "resourcefulness", "treehouse"]
  },

  // ─── SPANISH LANGUAGE BOOKS ───────────────────────────────────────────────
  {
    id: 201,
    title: "Cien años de soledad",
    author: "Gabriel García Márquez",
    cover: "https://covers.openlibrary.org/b/isbn/9788497592208-L.jpg",
    genre: ["Literary Fiction", "Classic"],
    language: "Spanish",
    year: 1967,
    rating: 4.8,
    description: "La saga épica de la familia Buendía a lo largo de siete generaciones en el pueblo mágico de Macondo, donde lo real convive con lo mítico en esta cumbre del realismo mágico latinoamericano.",
    pages: 471,
    isbn: "9788497592208",
    tags: ["realismo-magico", "familia", "macondo", "soledad"]
  },
  {
    id: 202,
    title: "Don Quijote de la Mancha",
    author: "Miguel de Cervantes",
    cover: "https://covers.openlibrary.org/b/isbn/9788420412146-L.jpg",
    genre: ["Classic", "Fiction", "Adventure"],
    language: "Spanish",
    year: 1605,
    rating: 4.7,
    description: "Las aventuras del ingenioso hidalgo Alonso Quijano, enloquecido por sus lecturas de novelas de caballerías, quien decide convertirse en caballero andante junto a su fiel escudero Sancho Panza.",
    pages: 1023,
    isbn: "9788420412146",
    tags: ["caballeria", "aventura", "ingenio", "clasico"]
  },
  {
    id: 203,
    title: "El amor en los tiempos del cólera",
    author: "Gabriel García Márquez",
    cover: "https://covers.openlibrary.org/b/isbn/9788497592277-L.jpg",
    genre: ["Literary Fiction", "Classic"],
    language: "Spanish",
    year: 1985,
    rating: 4.6,
    description: "Una historia de amor que trasciende el tiempo: Florentino Ariza espera más de cincuenta años para reunirse con Fermina Daza, la mujer de quien se enamoró siendo joven en Colombia.",
    pages: 388,
    isbn: "9788497592277",
    tags: ["amor", "espera", "colombia", "tiempo"]
  },
  {
    id: 204,
    title: "La casa de los espíritus",
    author: "Isabel Allende",
    cover: "https://covers.openlibrary.org/b/isbn/9788401352782-L.jpg",
    genre: ["Literary Fiction", "Historical Fiction"],
    language: "Spanish",
    year: 1982,
    rating: 4.6,
    description: "La saga de la familia Trueba a lo largo de varias generaciones en Chile, donde lo sobrenatural convive con la historia política y social del país en este debut magistral de Isabel Allende.",
    pages: 448,
    isbn: "9788401352782",
    tags: ["familia", "chile", "espiritus", "historia"]
  },
  {
    id: 205,
    title: "El alquimista",
    author: "Paulo Coelho",
    cover: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    genre: ["Fiction", "Philosophy", "Self-Help"],
    language: "Spanish",
    year: 1988,
    rating: 4.5,
    description: "Santiago, un joven pastor andaluz que sueña con encontrar un tesoro, emprende un viaje desde España hasta las pirámides de Egipto aprendiendo sobre el alma del mundo y la leyenda personal.",
    pages: 208,
    isbn: "9780062315007",
    tags: ["leyenda-personal", "suenos", "viaje", "filosofia"]
  },
  {
    id: 206,
    title: "Ficciones",
    author: "Jorge Luis Borges",
    cover: "https://covers.openlibrary.org/b/isbn/9788420435596-L.jpg",
    genre: ["Fiction", "Literary Fiction"],
    language: "Spanish",
    year: 1944,
    rating: 4.7,
    description: "Una colección de cuentos magistrales que exploran laberintos, bibliotecas infinitas y mundos alternativos, consolidando a Borges como uno de los grandes de la literatura universal.",
    pages: 174,
    isbn: "9788420435596",
    tags: ["laberintos", "cuentos", "filosofia", "universo"]
  },
  {
    id: 207,
    title: "Rayuela",
    author: "Julio Cortázar",
    cover: "https://covers.openlibrary.org/b/isbn/9788437604572-L.jpg",
    genre: ["Literary Fiction", "Contemporary Fiction"],
    language: "Spanish",
    year: 1963,
    rating: 4.5,
    description: "Una novela experimental que puede leerse en distintos órdenes, siguiendo a Horacio Oliveira en su búsqueda existencial entre París y Buenos Aires. Una obra revolucionaria de la narrativa latinoamericana.",
    pages: 736,
    isbn: "9788437604572",
    tags: ["experimental", "existencial", "paris", "juego"]
  },
  {
    id: 208,
    title: "Pedro Páramo",
    author: "Juan Rulfo",
    cover: "https://covers.openlibrary.org/b/isbn/9788437604633-L.jpg",
    genre: ["Literary Fiction", "Classic"],
    language: "Spanish",
    year: 1955,
    rating: 4.6,
    description: "Juan Preciado viaja al pueblo fantasma de Comala buscando a su padre Pedro Páramo, donde conviven los vivos y los muertos en una atmósfera mítica e inolvidable que influyó en toda la narrativa latinoamericana.",
    pages: 124,
    isbn: "9788437604633",
    tags: ["fantasmas", "mexico", "mito", "padre"]
  },
  {
    id: 209,
    title: "La ciudad y los perros",
    author: "Mario Vargas Llosa",
    cover: "https://covers.openlibrary.org/b/isbn/9788422209997-L.jpg",
    genre: ["Literary Fiction", "Classic"],
    language: "Spanish",
    year: 1963,
    rating: 4.5,
    description: "Ambientada en el Colegio Militar Leoncio Prado de Lima, esta novela narra el drama de honor, jerarquía y violencia institucional entre un grupo de cadetes en el Perú de los años cincuenta.",
    pages: 448,
    isbn: "9788422209997",
    tags: ["militar", "lima", "honor", "juventud"]
  },
  {
    id: 210,
    title: "Crónica de una muerte anunciada",
    author: "Gabriel García Márquez",
    cover: "https://covers.openlibrary.org/b/isbn/9788497592239-L.jpg",
    genre: ["Literary Fiction", "Mystery"],
    language: "Spanish",
    year: 1981,
    rating: 4.5,
    description: "Todo un pueblo sabe que Santiago Nasar va a ser asesinado, pero nadie logra impedirlo. García Márquez reconstruye el crimen anunciado a través de testimonios que revelan la complicidad del destino.",
    pages: 152,
    isbn: "9788497592239",
    tags: ["crimen", "destino", "colombia", "novela-corta"]
  },

  // ─── FRENCH LANGUAGE BOOKS ────────────────────────────────────────────────
  {
    id: 221,
    title: "Les Misérables",
    author: "Victor Hugo",
    cover: "https://covers.openlibrary.org/b/isbn/9782070408504-L.jpg",
    genre: ["Classic", "Historical Fiction"],
    language: "French",
    year: 1862,
    rating: 4.8,
    description: "L'épopée de Jean Valjean, forçat libéré qui cherche à se racheter dans la France du XIXe siècle, poursuivi par l'inspecteur Javert, dans cette oeuvre monumentale sur la justice et la compassion.",
    pages: 1463,
    isbn: "9782070408504",
    tags: ["justice", "redemption", "paris", "revolution"]
  },
  {
    id: 222,
    title: "Le Petit Prince",
    author: "Antoine de Saint-Exupéry",
    cover: "https://covers.openlibrary.org/b/isbn/9782070612758-L.jpg",
    genre: ["Classic", "Children", "Philosophy"],
    language: "French",
    year: 1943,
    rating: 4.9,
    description: "Un aviateur tombé en panne dans le Sahara rencontre un mystérieux petit prince venu d'une autre planète. Un conte poétique et philosophique sur l'amitié, l'amour et le sens de la vie.",
    pages: 96,
    isbn: "9782070612758",
    tags: ["planete", "amitie", "philosophie", "conte"]
  },
  {
    id: 223,
    title: "L'Étranger",
    author: "Albert Camus",
    cover: "https://covers.openlibrary.org/b/isbn/9782070360024-L.jpg",
    genre: ["Literary Fiction", "Classic", "Philosophy"],
    language: "French",
    year: 1942,
    rating: 4.6,
    description: "Meursault, un homme indifférent au monde qui l'entoure, commet un meurtre et fait face à la justice dans ce roman fondateur de la philosophie de l'absurde par Albert Camus.",
    pages: 186,
    isbn: "9782070360024",
    tags: ["absurde", "indifference", "algerie", "philosophie"]
  },
  {
    id: 224,
    title: "Notre-Dame de Paris",
    author: "Victor Hugo",
    cover: "https://covers.openlibrary.org/b/isbn/9782070408382-L.jpg",
    genre: ["Classic", "Historical Fiction"],
    language: "French",
    year: 1831,
    rating: 4.6,
    description: "Au coeur du Paris médiéval, le destin tragique de Quasimodo, sonneur de cloches bossu, et d'Esmeralda, belle danseuse, dans l'ombre majestueuse de la cathédrale Notre-Dame.",
    pages: 552,
    isbn: "9782070408382",
    tags: ["medieval", "paris", "cathedrale", "tragedie"]
  },
  {
    id: 225,
    title: "Le Rouge et le Noir",
    author: "Stendhal",
    cover: "https://covers.openlibrary.org/b/isbn/9782070360369-L.jpg",
    genre: ["Classic", "Literary Fiction"],
    language: "French",
    year: 1830,
    rating: 4.5,
    description: "Julien Sorel, fils d'un charpentier ambitieux, gravit les échelons de la société française de la Restauration dans ce roman psychologique magistral sur l'ambition et les illusions.",
    pages: 576,
    isbn: "9782070360369",
    tags: ["ambition", "societe", "psychologie", "ascension"]
  },
  {
    id: 226,
    title: "Germinal",
    author: "Émile Zola",
    cover: "https://covers.openlibrary.org/b/isbn/9782070410026-L.jpg",
    genre: ["Classic", "Historical Fiction"],
    language: "French",
    year: 1885,
    rating: 4.6,
    description: "Étienne Lantier descend dans les mines du nord de la France et devient le leader d'une grève ouvrière dans ce roman puissant sur les conditions de travail au XIXe siècle.",
    pages: 592,
    isbn: "9782070410026",
    tags: ["mines", "greve", "ouvriers", "naturalisme"]
  },
  {
    id: 227,
    title: "Le Père Goriot",
    author: "Honoré de Balzac",
    cover: "https://covers.openlibrary.org/b/isbn/9782070413850-L.jpg",
    genre: ["Classic", "Literary Fiction"],
    language: "French",
    year: 1835,
    rating: 4.5,
    description: "Dans une pension parisienne, le jeune Rastignac fait ses premières armes dans la société, témoignant du sacrifice absolu du père Goriot pour ses filles ingrates dans la Comédie humaine.",
    pages: 384,
    isbn: "9782070413850",
    tags: ["paris", "sacrifice", "societe", "ambition"]
  },
  {
    id: 228,
    title: "Les Fleurs du mal",
    author: "Charles Baudelaire",
    cover: "https://covers.openlibrary.org/b/isbn/9782070410071-L.jpg",
    genre: ["Poetry", "Classic"],
    language: "French",
    year: 1857,
    rating: 4.6,
    description: "Recueil de poèmes emblématiques explorant la beauté, le spleen et les profondeurs de l'âme humaine, oeuvre fondatrice de la poésie moderne française et de tout le symbolisme européen.",
    pages: 368,
    isbn: "9782070410071",
    tags: ["poesie", "spleen", "beaute", "modernite"]
  },
  {
    id: 229,
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    cover: "https://covers.openlibrary.org/b/isbn/9782070413119-L.jpg",
    genre: ["Classic", "Literary Fiction"],
    language: "French",
    year: 1857,
    rating: 4.5,
    description: "Emma Bovary, épouse d'un médecin de campagne, rêve d'une vie romantique et raffinée bien loin de sa réalité provinciale, dans ce chef-d'oeuvre du réalisme littéraire de Gustave Flaubert.",
    pages: 468,
    isbn: "9782070413119",
    tags: ["romantisme", "desillusion", "province", "realisme"]
  },
  {
    id: 230,
    title: "Les Trois Mousquetaires",
    author: "Alexandre Dumas",
    cover: "https://covers.openlibrary.org/b/isbn/9782070409419-L.jpg",
    genre: ["Classic", "Adventure", "Historical Fiction"],
    language: "French",
    year: 1844,
    rating: 4.7,
    description: "D'Artagnan, jeune Gascon plein d'ambition, arrive à Paris et se lie d'amitié avec trois mousquetaires du roi : Athos, Porthos et Aramis, dans des aventures pleines de bravoure et d'honneur.",
    pages: 720,
    isbn: "9782070409419",
    tags: ["mousquetaires", "aventure", "honneur", "paris"]
  },

  // ─── GERMAN LANGUAGE BOOKS ────────────────────────────────────────────────
  {
    id: 241,
    title: "Die Leiden des jungen Werthers",
    author: "Johann Wolfgang von Goethe",
    cover: "https://covers.openlibrary.org/b/isbn/9783150000724-L.jpg",
    genre: ["Classic", "Literary Fiction"],
    language: "German",
    year: 1774,
    rating: 4.3,
    description: "Der junge Werther verliebt sich unglücklich in die verlobte Lotte und versinkt in tiefer Melancholie. Goethes briefförmiger Roman begründete die Sturm-und-Drang-Bewegung und erschütterte ganz Europa.",
    pages: 176,
    isbn: "9783150000724",
    tags: ["liebe", "melancholie", "romantik", "klassiker"]
  },
  {
    id: 242,
    title: "Faust: Der Tragödie erster Teil",
    author: "Johann Wolfgang von Goethe",
    cover: "https://covers.openlibrary.org/b/isbn/9783150000014-L.jpg",
    genre: ["Classic", "Poetry", "Philosophy"],
    language: "German",
    year: 1808,
    rating: 4.6,
    description: "Der alternde Gelehrte Faust schließt einen Pakt mit dem Teufel Mephistopheles, um tieferes Wissen und die Fülle des Lebens zu erlangen — Goethes unsterbliches Meisterwerk der Weltliteratur.",
    pages: 464,
    isbn: "9783150000014",
    tags: ["teufel", "pakt", "wissen", "philosophie"]
  },
  {
    id: 243,
    title: "Der Prozess",
    author: "Franz Kafka",
    cover: "https://covers.openlibrary.org/b/isbn/9783150092735-L.jpg",
    genre: ["Literary Fiction", "Classic"],
    language: "German",
    year: 1925,
    rating: 4.5,
    description: "Josef K. wird eines Morgens ohne erkennbaren Grund verhaftet und einem absurden Gerichtsverfahren ausgesetzt, das sein Leben vollständig dominiert — Kafkas erschütterndes Meisterwerk über Bürokratie.",
    pages: 304,
    isbn: "9783150092735",
    tags: ["buerokratie", "absurd", "gericht", "kafka"]
  },
  {
    id: 244,
    title: "Die Verwandlung",
    author: "Franz Kafka",
    cover: "https://covers.openlibrary.org/b/isbn/9783150093368-L.jpg",
    genre: ["Literary Fiction", "Classic"],
    language: "German",
    year: 1915,
    rating: 4.5,
    description: "Gregor Samsa erwacht eines Morgens als riesiges Ungeziefer. Kafkas berühmteste Erzählung ist ein einzigartiges Gleichnis über Entfremdung, Familie und die menschliche Existenz.",
    pages: 96,
    isbn: "9783150093368",
    tags: ["verwandlung", "entfremdung", "familie", "absurd"]
  },
  {
    id: 245,
    title: "Siddhartha",
    author: "Hermann Hesse",
    cover: "https://covers.openlibrary.org/b/isbn/9783518365403-L.jpg",
    genre: ["Literary Fiction", "Philosophy", "Classic"],
    language: "German",
    year: 1922,
    rating: 4.7,
    description: "Der Brahmanensohn Siddhartha verlässt sein behütetes Leben und sucht Erleuchtung durch Askese, weltlichen Genuss und schließlich stille Selbstfindung am Fluss — Hesses bekanntestes Werk.",
    pages: 160,
    isbn: "9783518365403",
    tags: ["erleuchtung", "suche", "indien", "philosophie"]
  },
  {
    id: 246,
    title: "Im Westen nichts Neues",
    author: "Erich Maria Remarque",
    cover: "https://covers.openlibrary.org/b/isbn/9783462019339-L.jpg",
    genre: ["Historical Fiction", "Classic"],
    language: "German",
    year: 1929,
    rating: 4.8,
    description: "Paul Bäumer schildert die Schrecken des Ersten Weltkriegs aus der Perspektive eines jungen Soldaten — ein erschütterndes Anti-Kriegs-Meisterwerk von weltweiter Bedeutung und bleibendem Einfluss.",
    pages: 304,
    isbn: "9783462019339",
    tags: ["krieg", "soldaten", "trauma", "frieden"]
  },
  {
    id: 247,
    title: "Der Steppenwolf",
    author: "Hermann Hesse",
    cover: "https://covers.openlibrary.org/b/isbn/9783518365519-L.jpg",
    genre: ["Literary Fiction", "Classic", "Philosophy"],
    language: "German",
    year: 1927,
    rating: 4.4,
    description: "Harry Haller, ein vereinsamter Intellektueller, sieht sich selbst als Steppenwolf — halb Mensch, halb Wolf — und kämpft in der modernen Gesellschaft um Freiheit und innere Befreiung.",
    pages: 288,
    isbn: "9783518365519",
    tags: ["identitaet", "isolation", "modernitaet", "selbstfindung"]
  },
  {
    id: 248,
    title: "Das Parfum",
    author: "Patrick Süskind",
    cover: "https://covers.openlibrary.org/b/isbn/9783257228007-L.jpg",
    genre: ["Literary Fiction", "Historical Fiction", "Mystery"],
    language: "German",
    year: 1985,
    rating: 4.5,
    description: "Jean-Baptiste Grenouille, ein Mensch ohne eigenen Körpergeruch, entwickelt im Paris des 18. Jahrhunderts eine besessene Suche nach dem vollkommenen Duft in diesem fesselnden historischen Roman.",
    pages: 320,
    isbn: "9783257228007",
    tags: ["duft", "besessenheit", "paris", "sinne"]
  },
  {
    id: 249,
    title: "Buddenbrooks",
    author: "Thomas Mann",
    cover: "https://covers.openlibrary.org/b/isbn/9783596294312-L.jpg",
    genre: ["Literary Fiction", "Classic", "Historical Fiction"],
    language: "German",
    year: 1901,
    rating: 4.5,
    description: "Der Verfall einer angesehenen Lübecker Kaufmannsfamilie über vier Generationen — Thomas Manns erster großer Roman, der ihm später den Nobelpreis einbrachte und die deutsche Literatur prägte.",
    pages: 752,
    isbn: "9783596294312",
    tags: ["familie", "verfall", "luebeck", "buergertum"]
  },
  {
    id: 250,
    title: "Der Zauberberg",
    author: "Thomas Mann",
    cover: "https://covers.openlibrary.org/b/isbn/9783596294220-L.jpg",
    genre: ["Literary Fiction", "Classic", "Philosophy"],
    language: "German",
    year: 1924,
    rating: 4.4,
    description: "Hans Castorp besucht seinen Cousin in einem Schweizer Sanatorium und bleibt sieben Jahre, während er philosophischen Gesprächen lauscht und über Zeit, Tod und das Leben nachdenkt.",
    pages: 1008,
    isbn: "9783596294220",
    tags: ["sanatorium", "philosophie", "schweiz", "zeit"]
  }
];
